#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="supabase/functions/.env"

# _resend_key — read RESEND_API_KEY from ENV_FILE at call time (never
# hardcoded, never echoed).
_resend_key() {
  [[ -f "$ENV_FILE" ]] || { warn "$ENV_FILE not found"; exit 1; }
  local key; key=$(grep -E '^RESEND_API_KEY=' "$ENV_FILE" | tail -n1 | cut -d= -f2-)
  [[ -n "$key" ]] || { warn "RESEND_API_KEY not set in $ENV_FILE"; exit 1; }
  printf '%s' "$key"
}

# _resend GET|POST path [json-body] — call the Resend API, print body to
# stdout, and return the HTTP status via $REPLY_STATUS. Never dies on a
# non-2xx response (set -e safe) so callers can decide what to do.
_resend() {
  local method="$1" path="$2" body="${3:-}" key resp status
  key=$(_resend_key)
  if [[ -n "$body" ]]; then
    resp=$(curl -sS -o /tmp/resend_resp.$$ -w '%{http_code}' -X "$method" \
      "https://api.resend.com${path}" \
      -H "Authorization: Bearer ${key}" \
      -H 'Content-Type: application/json' \
      -d "$body") || true
  else
    resp=$(curl -sS -o /tmp/resend_resp.$$ -w '%{http_code}' -X "$method" \
      "https://api.resend.com${path}" \
      -H "Authorization: Bearer ${key}") || true
  fi
  status="$resp"
  REPLY_STATUS="$status"
  cat /tmp/resend_resp.$$ 2>/dev/null
  rm -f /tmp/resend_resp.$$
}

banner "Resend domain verification"

# ── Stage 1: which domain ──────────────────────────────────────────────────
stage "Which domain"
say "OTP emails only reach the account owner's own inbox right now because"
say "the Resend account has zero verified domains — it's stuck in sandbox mode."
say "This wizard adds a domain to Resend, walks you through the DNS records,"
say "and waits for verification."
note "You need control of DNS for the domain (access to add TXT/CNAME/MX records"
note "at whatever registrar or DNS host manages it)."
_current_from=$(_existing EMAIL_FROM || true)
_default_domain="${_current_from##*@}"
_default_domain="${_default_domain%>}"
[[ -n "$_default_domain" ]] || _default_domain="sigap.id"
if [[ -z "$(_existing DOMAIN || true)" ]]; then
  write_env DOMAIN "$_default_domain" >/dev/null
fi
ask DOMAIN "Domain to verify with Resend:"
say "Using domain: ${BOLD}${DOMAIN}${RESET}"

# ── Stage 2: add (or reuse) the domain in Resend ────────────────────────────
stage "Register domain with Resend"
say "Checking whether ${DOMAIN} is already registered in this Resend account..."
_list_body=$(_resend GET "/domains")
if [[ "$REPLY_STATUS" != 2* ]]; then
  warn "Resend API returned HTTP $REPLY_STATUS listing domains:"
  note "$_list_body"
  exit 1
fi
DOMAIN_ID=$(printf '%s' "$_list_body" | grep -o "\"id\":\"[^\"]*\",\"name\":\"${DOMAIN}\"" | head -n1 | sed -E 's/.*"id":"([^"]*)".*/\1/')
if [[ -z "$DOMAIN_ID" ]]; then
  # name may appear before id in the object depending on API version — try both orders.
  DOMAIN_ID=$(printf '%s' "$_list_body" \
    | tr '{' '\n' \
    | grep -F "\"name\":\"${DOMAIN}\"" \
    | head -n1 \
    | grep -o '"id":"[^"]*"' \
    | sed -E 's/"id":"([^"]*)"/\1/')
fi

if [[ -n "$DOMAIN_ID" ]]; then
  say "Found existing domain in Resend — reusing it (id ${DOMAIN_ID})."
  _create_body="$_list_body"
  DOMAIN_RECORDS_SOURCE="get"
else
  say "Not registered yet — creating it now."
  _create_body=$(_resend POST "/domains" "{\"name\":\"${DOMAIN}\"}")
  if [[ "$REPLY_STATUS" != 2* ]]; then
    warn "Resend API returned HTTP $REPLY_STATUS creating the domain:"
    note "$_create_body"
    exit 1
  fi
  DOMAIN_ID=$(printf '%s' "$_create_body" | grep -o '"id":"[^"]*"' | head -n1 | sed -E 's/"id":"([^"]*)"/\1/')
  [[ -n "$DOMAIN_ID" ]] || { warn "couldn't parse domain id from Resend response"; note "$_create_body"; exit 1; }
  say "Created domain in Resend (id ${DOMAIN_ID})."
  DOMAIN_RECORDS_SOURCE="create"
fi
write_env RESEND_DOMAIN_ID "$DOMAIN_ID"

# The create response includes records inline; when reusing an existing
# domain, fetch it fresh to get the current records array.
if [[ "$DOMAIN_RECORDS_SOURCE" == "get" ]]; then
  _detail_body=$(_resend GET "/domains/${DOMAIN_ID}")
  if [[ "$REPLY_STATUS" != 2* ]]; then
    warn "Resend API returned HTTP $REPLY_STATUS fetching domain details:"
    note "$_detail_body"
    exit 1
  fi
else
  _detail_body="$_create_body"
fi

say ""
say "${BOLD}DNS records to add for ${DOMAIN}:${RESET}"
note "(type, host/name, value, priority/ttl where applicable)"
say ""
printf '%s' "$_detail_body" | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
records = data.get("records", [])
if not records:
    print("  (no records returned — the domain may already be fully configured)")
for r in records:
    rec = r.get("record", "?")
    typ = r.get("type", "?")
    name = r.get("name", "?")
    value = r.get("value", "?")
    priority = r.get("priority")
    ttl = r.get("ttl", "Auto")
    line = f"  [{rec}] {typ}  name={name}  value={value}"
    if priority is not None:
        line += f"  priority={priority}"
    line += f"  ttl={ttl}"
    print(line)
' 2>/dev/null || note "$_detail_body"
say ""
pause "Copy these down (or keep this terminal open), then press Enter to continue"

# ── Stage 3: add the DNS records ────────────────────────────────────────────
stage "Add the DNS records"
say "Log into whichever service manages DNS for ${BOLD}${DOMAIN}${RESET} — your"
say "domain registrar, or wherever nameservers point (Cloudflare, Route53, etc.)."
step "Add each record printed in the previous stage exactly as shown:"
note "  - TXT/MX records for SPF"
note "  - TXT record(s) for DKIM"
note "  - Any Tracking CNAME, if present"
warn "Don't alter existing records for this domain unless Resend's record"
warn "explicitly replaces one (e.g. an existing catch-all TXT/SPF record may"
warn "need merging rather than duplicating)."
pause "Press Enter once you've added all the records"

# ── Stage 4: trigger + poll verification ────────────────────────────────────
stage "Verify with Resend"
say "Asking Resend to check DNS now..."
_verify_body=$(_resend POST "/domains/${DOMAIN_ID}/verify")
if [[ "$REPLY_STATUS" != 2* ]]; then
  warn "Resend API returned HTTP $REPLY_STATUS triggering verification:"
  note "$_verify_body"
  note "You can re-run this script later to retry — it'll reuse the saved domain id."
  exit 1
fi
say "Verification triggered. Polling status..."

while true; do
  _status_body=$(_resend GET "/domains/${DOMAIN_ID}")
  if [[ "$REPLY_STATUS" != 2* ]]; then
    warn "Resend API returned HTTP $REPLY_STATUS checking status:"
    note "$_status_body"
  else
    _status=$(printf '%s' "$_status_body" | grep -o '"status":"[^"]*"' | head -n1 | sed -E 's/"status":"([^"]*)"/\1/')
    say "Current status: ${BOLD}${_status:-unknown}${RESET}"
    if [[ "$_status" == "verified" ]]; then
      say "${GREEN}Domain verified.${RESET}"
      break
    fi
  fi
  warn "Not verified yet. DNS propagation can take anywhere from a few minutes"
  warn "to several hours depending on your DNS provider and record TTLs."
  if confirm "Check again now?"; then
    continue
  else
    note "No problem — nothing else to do right now. Re-run this script later:"
    note "  ENV_FILE=supabase/functions/.env ./scripts/setup-resend-domain.sh"
    note "It will skip straight to polling since the domain (id ${DOMAIN_ID}) is already saved."
    exit 0
  fi
done

# ── Stage 5: wire the domain into app config ────────────────────────────────
stage "Wire domain into app config"
_current_from=$(_existing EMAIL_FROM || true)
_current_from_domain="${_current_from##*@}"
_current_from_domain="${_current_from_domain%>}"

if [[ "$_current_from_domain" == "$DOMAIN" ]]; then
  say "EMAIL_FROM already uses ${DOMAIN} — no code/config change needed."
  say "Domain verification lives entirely on Resend's side, not in the function"
  say "code, so the already-deployed auth-request-otp function starts working"
  say "immediately now that ${DOMAIN} is verified."
else
  say "EMAIL_FROM currently points at a different domain (${_current_from_domain:-unset})."
  _new_from="SIGAP <otp@${DOMAIN}>"
  write_env EMAIL_FROM "$_new_from"
  say "Updated local EMAIL_FROM to: ${_new_from}"
  warn "This only affects local dev. The deployed auth-request-otp function"
  warn "reads its own environment — you must ALSO update the Supabase Cloud secret:"
  note "  supabase secrets set EMAIL_FROM='${_new_from}'"
  note "(or set it via the Supabase dashboard → Edge Functions → Secrets)"
fi

finish
