import type { ComplaintDetail } from '@repo/supabase';

// Aduan contoh di sekitar Bandung supaya peta & daftar selalu punya isi
// walau belum ada aduan sungguhan di sekitar lokasi pengguna. ID diawali
// `dummy-` supaya layar detail (`aduan/[id].tsx`) tahu harus memakai data
// ini alih-alih memanggil `getComplaint`.
export const DUMMY_COMPLAINTS: ComplaintDetail[] = [
  {
    id: 'dummy-dago-1',
    title: 'Jalan berlubang depan Warung Kopi Purnama',
    description: 'Lubang besar di badan jalan bikin motor oleng, sudah beberapa kali ada yang jatuh.',
    category: 'jalan_rusak',
    assignedDinas: 'pupr',
    urgency: 'P0',
    status: 'verified',
    locationLat: -6.8918,
    locationLng: 107.6139,
    kelurahan: 'Dago',
    kecamatan: 'Coblong',
    imageUrls: [],
    upvoteCount: 18,
    slaDueAt: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    locationAddress: 'Jl. Ir. H. Djuanda No. 112, Dago',
    aiSummary: 'Lubang besar di badan jalan berpotensi membahayakan pengendara motor.',
    rejectionReason: null,
    dinasName: 'Dinas Pekerjaan Umum dan Penataan Ruang',
    userId: 'dummy-user-rian',
    authorName: 'Rian Ardiansyah',
  },
  {
    id: 'dummy-cipaganti-1',
    title: 'Tumpukan sampah tidak diangkut 3 hari',
    description: 'Sampah menumpuk di pinggir Jl. Cipaganti dan mulai berbau.',
    category: 'sampah',
    assignedDinas: 'dlh',
    urgency: 'P1',
    status: 'in_progress',
    locationLat: -6.8985,
    locationLng: 107.6034,
    kelurahan: 'Cipaganti',
    kecamatan: 'Coblong',
    imageUrls: [],
    upvoteCount: 9,
    slaDueAt: new Date(Date.now() + 1000 * 60 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    locationAddress: 'Jl. Cipaganti No. 45, Cipaganti',
    aiSummary: 'Sampah rumah tangga menumpuk selama tiga hari dan mulai menimbulkan bau.',
    rejectionReason: null,
    dinasName: 'Dinas Lingkungan Hidup',
    userId: 'dummy-user-sri',
    authorName: 'Sri Wulandari',
  },
  {
    id: 'dummy-sukamaju-1',
    title: 'Lampu lalu lintas mati total',
    description: 'Traffic light di persimpangan Sukamaju padam sejak semalam, rawan kecelakaan.',
    category: 'lampu_lalu_lintas',
    assignedDinas: 'dishub',
    urgency: 'P2',
    status: 'resolved',
    locationLat: -6.8756,
    locationLng: 107.6259,
    kelurahan: 'Sukamaju',
    kecamatan: 'Cibeunying Kaler',
    imageUrls: [],
    upvoteCount: 4,
    slaDueAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    locationAddress: 'Simpang Jl. Sukamaju - Jl. PHH Mustofa, Sukamaju',
    aiSummary: 'Lampu lalu lintas padam total di persimpangan ramai, berisiko kecelakaan.',
    rejectionReason: null,
    dinasName: 'Dinas Perhubungan',
    userId: 'dummy-user-agus',
    authorName: 'Agus Setiawan',
  },
  {
    id: 'dummy-riau-1',
    title: 'Drainase tersumbat di Jl. Riau',
    description: 'Selokan penuh sedimen sehingga air meluap ke trotoar saat hujan.',
    category: 'drainase',
    assignedDinas: 'pupr',
    urgency: 'P1',
    status: 'verified',
    locationLat: -6.9013,
    locationLng: 107.6186,
    kelurahan: 'Citarum',
    kecamatan: 'Bandung Wetan',
    imageUrls: [],
    upvoteCount: 12,
    slaDueAt: new Date(Date.now() + 1000 * 60 * 60 * 40).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    locationAddress: 'Jl. Riau No. 88, Citarum',
    aiSummary: 'Sedimen menyumbat saluran drainase sehingga air meluap ke trotoar saat hujan.',
    rejectionReason: null,
    dinasName: 'Dinas Pekerjaan Umum dan Penataan Ruang',
    userId: 'dummy-user-fitri',
    authorName: 'Fitri Handayani',
  },
  {
    id: 'dummy-tamansari-1',
    title: 'Pohon tumbang menutup jalur pejalan kaki',
    description: 'Pohon besar tumbang akibat angin kencang, menutup separuh trotoar Tamansari.',
    category: 'pohon_tumbang',
    assignedDinas: 'dlh',
    urgency: 'P0',
    status: 'in_progress',
    locationLat: -6.8975,
    locationLng: 107.6067,
    kelurahan: 'Tamansari',
    kecamatan: 'Bandung Wetan',
    imageUrls: [],
    upvoteCount: 21,
    slaDueAt: new Date(Date.now() + 1000 * 60 * 60 * 8).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    locationAddress: 'Jl. Tamansari No. 23, Tamansari',
    aiSummary: 'Pohon tumbang menutup sebagian trotoar akibat angin kencang, menghalangi pejalan kaki.',
    rejectionReason: null,
    dinasName: 'Dinas Lingkungan Hidup',
    userId: 'dummy-user-bayu',
    authorName: 'Bayu Nugraha',
  },
  {
    id: 'dummy-cihapit-1',
    title: 'Parkir liar memakan badan jalan',
    description: 'Kendaraan parkir sembarangan di Cihapit bikin jalan menyempit dan macet.',
    category: 'parkir_liar',
    assignedDinas: 'dishub',
    urgency: 'P2',
    status: 'resolved',
    locationLat: -6.9057,
    locationLng: 107.6154,
    kelurahan: 'Cihapit',
    kecamatan: 'Bandung Wetan',
    imageUrls: [],
    upvoteCount: 6,
    slaDueAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    locationAddress: 'Jl. Cihapit No. 17, Cihapit',
    aiSummary: 'Kendaraan parkir sembarangan mempersempit badan jalan dan menimbulkan kemacetan.',
    rejectionReason: null,
    dinasName: 'Dinas Perhubungan',
    userId: 'dummy-user-nadia',
    authorName: 'Nadia Puspita',
  },
];

/** Cari aduan contoh berdasarkan id (`dummy-...`) — dipakai layar feed & detail. */
export function findDummyComplaint(id: string): ComplaintDetail | undefined {
  return DUMMY_COMPLAINTS.find((c) => c.id === id);
}
